# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NEMEA
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  System for network traffic analysis and anomaly detection.
baseurl: "/Nemea" # the subpath of your site, e.g. /blog
url: "http://cesnet.github.io/" # the base hostname & protocol for your site
twitter_username: NEMEA_System
github_username:

# Build settings
markdown: kramdown
